name: mycart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.18.3
  firebase_core : ^0.5.0+1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: "^0.8.0"
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  fluttertoast: ^7.1.6
  flutter_spinkit: "^4.1.2"
  auto_size_text: ^2.1.0
  confirm_dialog: ^0.1.1
  intl: ^0.16.1
  firebase_messaging: ^7.0.3
  awesome_notifications: ^0.0.5+4
  firebase_database: ^4.4.0
  google_maps_flutter: ^1.0.3
  json_serializable: ^3.3.0
  provider: ^5.0.0



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

dev_dependencies:
  build_runner: ^1.10.0
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/main/back.png
    - assets/images/main/logo.png
    - assets/images/main/logo_c.png
    - assets/images/ic_launcher.png
    - assets/images/cat.png
    - assets/images/loc.png
    - assets/images/noti.png
    - assets/images/other_icons/cart_sm.png
    - assets/images/other_icons/cart_lg.png
    - assets/images/other_icons/bike_lg.png
    - assets/images/other_icons/back_arrow.png
    - assets/images/other_icons/user_avatar.png
    - assets/images/social/facebook_logo.png
    - assets/images/social/google_logo.png
    - assets/images/holders/banner_holder.png
    - assets/images/holders/main_menu_item_holder.png
    - assets/images/holders/sub_menu_item_holder.png
    - assets/images/holders/item_holder.png
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-assets/images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-assets/images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
